name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Alb you degenerate!"
      - name: Print goodbye
        run: echo "Time to sleep Done - bye!"

